
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import static java.sql.JDBCType.NULL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author abushan
 */
public class Piano extends javax.swing.JFrame {

    private Object formatter;

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gigi", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PIANO");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("F1");
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 50, 150));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("C");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 150));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("D");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 50, 150));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("E");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, 150));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("F");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 50, 150));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("G");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 50, 150));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("A");
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 50, 150));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("B");
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 50, 150));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("C1");
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 150));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("D1");
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, 150));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("E1");
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 50, 150));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("D#1");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 90, 70, 120));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("C");
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 50, 150));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("C#");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 120));

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("D#");
        jButton15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, 120));

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("F#");
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 120));

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("G#");
        jButton17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, 120));

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Bb");
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 70, 120));

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("C#1");
        jButton19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 70, 120));

        jTextField1.setUI(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D_s1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C_s.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D_s.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F_s.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\G_s.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\Bb.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C_s1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            writeToLog("C");
        } catch (IOException ex) {
            Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\E.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\G.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\A.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\B.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\E1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F1.wav";
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       
        if (evt.getKeyCode() == KeyEvent.VK_A) {
                   

            try {

                String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C.wav";
                AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                Clip player = AudioSystem.getClip();
                player.open(audio);
                player.start();

            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                            }
            
                try {

                    writeToLog("C");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_S) {
                try {
                    writeToLog("D");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_D) {
                try {
                    writeToLog("E");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\E.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_F) {
                try {
                    writeToLog("F");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_G) {
                try {
                    writeToLog("G");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\G.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_H) {
                try {
                    writeToLog("H");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\A.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_J) {
                try {
                    writeToLog("B");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\B.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_K) {
                try {
                    writeToLog("C1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_L) {
                try {
                    writeToLog("D1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_SEMICOLON) {
                try {
                    writeToLog("E1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\E1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_QUOTE) {
                try {
                    writeToLog("F1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_Q) {
                try {
                    writeToLog("C_s");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C_s.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_W) {
                try {
                    writeToLog("D_s");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D_s.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_E) {
                try {
                    writeToLog("F_s");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\F_s.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_R) {
                try {
                    writeToLog("G_s");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\G_s.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_T) {
                try {
                    writeToLog("Bb");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\Bb.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_Y) {
                try {
                    writeToLog("C_s1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\C_s1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }
            if (evt.getKeyCode() == KeyEvent.VK_U) {

                try {
                    writeToLog("D_s1");
                } catch (IOException ex) {
                    Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    String path = "D:\\avas\\Java\\PianoProject\\Music_Note\\D_s1.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
            }


    }//GEN-LAST:event_jTextField1KeyPressed

    
    

    private void writeToLog(String message) throws IOException {
        String date = new SimpleDateFormat("HH.mm").format(new Date());
        BufferedWriter writer = new BufferedWriter(new FileWriter("D:/avas/Java/PianoProject/Keys/Notes"+date+".txt", true));
        writer.write(message + "   ");
        writer.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Piano().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
